apiVersion: v1
kind: Pod
metadata:
  name: pod-demo
  namespace: practice
spec:
  containers:
  - name: database
    image: mongo
    ports:
    - containerPort: 27017
    env:
    - name: MONGO_INITDB_ROOT_USERNAME
      value: root
    - name: MONGO_INITDB_ROOT_PASSWORD
      value: root
  - name: mongo-ui
    image: mongo-express
    ports:
    - containerPort: 8081
    env:
    - name: MONGO_INITDB_ROOT_USERNAME
      value: root
    - name: MONGO_INITDB_ROOT_PASSWORD
      value: root
    - name: ME_CONFIG_MONGODB_URL
      value: mongodb://root:root@localhost:27017/
  - name: backend
    image: project-backend
    ports:
    - containerPort: 3001
    imagePullPolicy: Never
  - name: frontend
    image: project-frontend
    imagePullPolicy: Never
  restartPolicy: Never


# commands:
# kubectl apply -f Pod.yml
# kubectl port-forward pod-demo 3009:3000 27017:27017 3007:8081 3001:3001 -n practice
# Note: - name: ME_CONFIG_MONGODB_URL
#       value: mongodb://root:root@localhost:27017/
