apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: practice2
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "database"
