apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: practice2
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: project-backend
        ports:
        - containerPort: 3001
        imagePullPolicy: Never
        env:
        - name: MONGO_USER
          valueFrom:
            secretKeyRef:
              name: db-user-pwd
              key: mongo-user
        - name: MONGO_PWD
          valueFrom:
            secretKeyRef:
              name: db-user-pwd
              key: mongo-password
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: practice2
spec:
  type: NodePort
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001
    nodePort: 30006
